Models/DbContext.cs
using System;
using Microsoft.EntityFrameworkCore;

namespace Assignment3Movies.Models
{
    //this is the model that creates a movie model from the sqlite database
    public class MovieDbContext : DbContext
    {

        public MovieDbContext(DbContextOptions<MovieDbContext> options) : base(options)
        {

        }
        //book objects for the database
        public DbSet<movie> movies { get; set; }
    }
}
 

Models/ErrorViewModel.cs
using System;

namespace Assignment3Movies.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment3Movies.Models
{
   //movie model
    public class movie
    {   
        [Required]
        [Key]
        public int movieID { get; set; }
        [Required]
        public string Category { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Year { get; set; }
        [Required]
        public string Director { get; set; }

        [Required]
        public string Rating { get; set; }
      
        public bool Edited { get; set; }
       
        public string LentTo { get; set; }
      
        public string Notes { get; set; }
    }
}

Controllers/HomeController.cs
using Assignment3Movies.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment3Movies.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            //view index
            return View();
        }

        public IActionResult bacon()
        {
            //view podcast page
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/moviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Assignment3Movies.Models;

namespace Assignment3Movies.Controllers
{
    public class moviesController : Controller
    {
        private readonly MovieDbContext _context;

        public moviesController(MovieDbContext context)
        {
            _context = context;
        }

        // GET: movies
        public async Task<IActionResult> Index()
        {
            return View(await _context.movies.ToListAsync());
        }

        // GET: movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.movies
                .FirstOrDefaultAsync(m => m.movieID == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: movies/Create
        public IActionResult Create()
        {
            //create movie form
            return View();
        }

        // POST: movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("movieID,Category,Title,Year,Director,Rating,Edited,LentTo,Notes")] movie movie)
        {
            //onsubmit of added movie
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            //edit movie
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("movieID,Category,Title,Year,Director,Rating,Edited,LentTo,Notes")] movie movie)
        {
            //make changes to editted movie
            if (id != movie.movieID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!movieExists(movie.movieID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            //delete movie
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.movies
                .FirstOrDefaultAsync(m => m.movieID == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //remove movie from database
          
            var movie = await _context.movies.FindAsync(id);
            _context.movies.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool movieExists(int id)
        {
            return _context.movies.Any(e => e.movieID == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Joel Hilton Welcome Page";
}

    <!--index with minimal stuff-->
    <div class="yessir">
        <h1>The Joel Hilton Film Collection</h1>
        <br />
        <a href="https://www.facebook.com/joelrhilton"><img src="~/JoelHilton.jpg" /></a>


    </div>




 

Views/Home/bacon.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Click On the Link to Access My Podcast! ";
}

<html>
<body>
    <!--bacon cshtml page with minimal stuff -->
    <h3>@ViewBag.Title</h3>
    <a href="https://baconsale.com/">
        <img src="~/baconsale3.png" class="thumbnail" />
    </a>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Joel Hilton</title>
    <link rel="favicon" type="image/x-icon" href="~/favicon.jpg" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Antic+Slab&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<nav class="egg navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" asp-controller="Home" asp-action="index">JOEL HILTON</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" asp-controller="Home" asp-action="index">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Home" asp-action="bacon">My podcast</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="movies" asp-action="Create">Add to List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="movies" asp-action="Index">Movie List</a>
            </li>
        </ul>
    </div>
</nav>
<!--layout page to have it link in all pages. gives the link and renders the body for all of them. -->

<body>
    @RenderBody()
    @RenderSection("Scripts", required: false)

</body>
</html>

Views/movies/Create.cshtml
@model Assignment3Movies.Models.movie

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--form to add a movie to the database-->
<h1>Add a movie to our movie list database!</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Director" class="control-label"></label>
                <input asp-for="Director" class="form-control" />
                <span asp-validation-for="Director" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating">Rating: </label>
                <select asp-for="Rating">
                    <option value="G">G</option>
                    <option value="PG">PG</option>
                    <option value="PG-13">PG-13</option>
                    <option value="R">R</option>
                </select>
            <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
  
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Edited" /> @Html.DisplayNameFor(model => model.Edited)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="LentTo" class="control-label"></label>
                <input asp-for="LentTo" class="form-control" />
                <span asp-validation-for="LentTo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/movies/Delete.cshtml
@model Assignment3Movies.Models.movie

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--form to delete a movie from the database-->
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>movie</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Director)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Director)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Edited)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Edited)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LentTo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LentTo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="movieID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/movies/Details.cshtml
@model Assignment3Movies.Models.movie

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--page that shows details of a movie in the database-->
<h1>Movie Details</h1>

<div>
    <h4>movie</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Director)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Director)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Edited)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Edited)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LentTo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LentTo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.movieID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/movies/Edit.cshtml
@model Assignment3Movies.Models.movie

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--form to edit a movie in the database-->
<h1>Edit Movie Information</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="movieID" />
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Director" class="control-label"></label>
                <input asp-for="Director" class="form-control" />
                <span asp-validation-for="Director" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating">Rating: </label>
                <select asp-for="Rating">
                    <option value="G">G</option>
                    <option value="PG">PG</option>
                    <option value="PG-13">PG-13</option>
                    <option value="R">R</option>
                </select>
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Edited" /> @Html.DisplayNameFor(model => model.Edited)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="LentTo" class="control-label"></label>
                <input asp-for="LentTo" class="form-control" />
                <span asp-validation-for="LentTo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/movies/Index.cshtml
@model IEnumerable<Assignment3Movies.Models.movie>

@{
    ViewData["Title"] = "Movie List Database";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--table that shows the movies in a database-->
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Director)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Edited)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LentTo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Director)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Edited)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LentTo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Notes)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.movieID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.movieID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.movieID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>